### ISSUE TITLE
demo sayfası

### ISSUE THREAD

**Issue by stnc** [oguzhanoya/jquery-steps#16]
bu demo sayfasının kodlarını paylaşbilir misin hocam güzelmiş 
birde oraya diğer örnekleride atarsan bence tadından yenmez

**Comment by oguzhanoya** [comment]
Teşekkür ederim, demo sayfası için "[gh-pages](https://github.com/oguzhanoya/jquery-steps/tree/gh-pages)" branch'ina bakabilirsin.
