### ISSUE TITLE
onFinish - set last step doneClass

### ISSUE THREAD

**Issue by rakucmr** [oguzhanoya/jquery-steps#22]
Hello,

Is there a way to set doneClass to last step selecter on onFinish event?

**Comment by jobalma** [comment]
Hi! you can remove the class _active_ and add class _done_ to the steps

something like this

` 
  $('#demo').steps({
    onFinish: function () {
      $('.step-steps li').removeClass('active').addClass('done');
    }
  });
`

**Comment by rakucmr** [comment]
Thanks
