### ISSUE TITLE
Support for async validation

### ISSUE THREAD

**Issue by hosseinitabar** [oguzhanoya/jquery-steps#26]
Hi

Thank you for this amazing library.

In a new web app I have to create dynamic tabs with dynamics fields in them. I don't know how many tabs there are, and I don't know how many fields exists in each tab.

Thus on clicking next, I have to raise an event ( **validationRequested**) and wait for all fields of the current tab to validate and return. Some of those fields need to validate based on server, thus they might take even some seconds before validation results can be known.

Here's the code I come up with. But it does not work:

```
onChange: function (currentIndex, newIndex, stepDirection) {
	if (stepDirection === "backward" || stepDirection === "none") {
		return true;
	}
	if (app.allowChangeToNextStep) {
		app.allowChangeToNextStep = false;
		return true;
	}
	var stepFields = app.findScopeFields($('#wizardForm .step-tab-panel[data-step=step' + (currentIndex + 1) + ']'));
	var fieldsThatNeedValidation = app.filterFieldsThatNeedValidation(stepFields);
	app.validateForm(fieldsThatNeedValidation)
		.then(function (submissionResults) {
			if (submissionResults.success) {
				app.allowChangeToNextStep = true;
				wizard.data('plugin_Steps').next();
			}
			return false;
		})
		.catch(function (error) {
			console.error(error);
		});
	return false;
},
```

This causes to go forward two steps.

Can you provide built-in support for async scenarios?

**Comment by oguzhanoya** [comment]
Hi, Thank you @hosseinitabar 

I've added an [example](https://github.com/oguzhanoya/jquery-steps/blob/master/examples/async.html) of async.
