### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Log1x** [oguzhanoya/jquery-steps#4]
I was curious if you'd mind publishing jquery-steps to npm? It looks like the name `jquery-steps` is taken, but you could change `name` in [package.json](https://github.com/oguzhanoya/jquery-steps/blob/master/package.json) to `jquery.steps` which is available and then `npm publish` and it'd allow for much easier package management when using webpack.

**Comment by oguzhanoya** [comment]
Thank you for the name suggestion. I published at npm. :blush:
