### ISSUE TITLE
Bug with switching to next select2 selector.

### ISSUE THREAD

**Issue by KuNman** [oguzhanoya/jquery-steps#5]
I have few steps. When I switch to next dropdown selector is _cutted_ to 1px. Only 1st selector displays correctly.
Someone had this bug before?
![image](https://user-images.githubusercontent.com/25631854/30944062-ae2e3e9e-a3f5-11e7-81e9-0724ca4ab339.png)
```
    $('#demo').steps({
        onFinish: function(1, 2, forward){return true;}
    });
```
Error : Uncaught SyntaxError: Unexpected number

**Comment by oguzhanoya** [comment]
This is not a bug. You can edit the style.

Add the following code into your css file:

```
#demo .step-app > .step-steps > li > a {
  border-right: 0;
}
```

onFinish function does not take parameters. Only onChange function can take parameters.

**Comment by KuNman** [comment]
That was mistake, of course there was onChange.
`    $('#demo').steps({
        onChange: function(1, 2, forward){return true;}
    });`
Uncaught SyntaxError: Unexpected number
I added this style but next selectors are still broken.
